# Generated by Django 5.0.2 on 2024-03-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0128_appareils_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='instructionsappareils',
            name='reponse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.reponseinstructions'),
        ),
    ]
