# Generated by Django 5.0.2 on 2024-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0132_etapes_remove_formule_specialite_controles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapes',
            name='num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
