# Generated by Django 5.0.2 on 2024-03-06 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0133_alter_etapes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='type_appareil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typeappareil'),
        ),
    ]
