# Generated by Django 5.0.2 on 2024-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0134_composition_type_appareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionsappareils',
            name='button',
            field=models.BooleanField(default=False),
        ),
    ]
