# Generated by Django 5.0.2 on 2024-03-07 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0135_instructionsappareils_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('structure_formulaire', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='controles',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='controles',
            name='resettable',
        ),
        migrations.RemoveField(
            model_name='controles',
            name='type_appareil',
        ),
        migrations.AddField(
            model_name='controles',
            name='controleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controles',
            name='date_heure',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='controles',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='controles',
            name='num_fiche',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='controles',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controles',
            name='appareil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='PPH.appareils'),
        ),
        migrations.AddField(
            model_name='controles',
            name='type_controle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='PPH.typecontrole'),
        ),
    ]
