# Generated by Django 5.0.2 on 2024-03-08 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0136_typecontrole_remove_controles_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controles',
            name='type_controle',
        ),
        migrations.AddField(
            model_name='typecontrole',
            name='type_appareil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typeappareil'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='controle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.typecontrole'),
        ),
        migrations.AlterField(
            model_name='typecontrole',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PPH.etapes'),
        ),
    ]
