# Generated by Django 5.0.2 on 2024-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0138_alter_typecontrole_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecontrole',
            name='description',
            field=models.JSONField(),
        ),
    ]
