# Generated by Django 5.0.2 on 2024-03-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0139_alter_typecontrole_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecontrole',
            name='description',
        ),
    ]
