# Generated by Django 5.0.2 on 2024-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0140_remove_typecontrole_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formule',
            name='controle',
        ),
        migrations.AddField(
            model_name='formule',
            name='controles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
