# Generated by Django 5.0.2 on 2024-03-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPH', '0142_personna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personna',
            name='competences',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='personna',
            name='profil',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='personna',
            name='situations',
            field=models.JSONField(null=True),
        ),
    ]
